In [1]:
##### REQUIRES THE DATAFRAME FOLDER TO BE NAMED 'Cohorts', WHICH INCLUDES ALL PRECOMPUTED DATAFRAMES #####
import fiber
from fiber.cohort import Cohort
from fiber.condition import Patient, MRNs
from fiber.condition import Diagnosis
from fiber.condition import Measurement, Encounter, Drug
from fiber.storage import yaml as fiberyaml
import pandas as pd
import pyarrow.parquet as pq
import numpy as np
import os
from functools import reduce

DB Password: ········

In [ ]:
### CASE BMI ###

In [2]:
#Case_filtered_15_540_Heights = pq.read_table('Cohorts/Case/Case_filtered_15_540_Heights.parquet').to_pandas()
#Case_filtered_15_540_Weights = pq.read_table('Cohorts/Case/Case_filtered_15_540_Weights.parquet').to_pandas()

BMI_Cases_1 = pq.read_table('Cohorts/Case/Measurement/BMI/BMI_cases.parquet').to_pandas()

In [3]:
# ready model for BMI Cases with 180 days gap 
BMI_Cases_1

,age_in_days,Weight_in_kg,HT_Onset,Height_in_cm,BMI
medical_record_number,,,,,
1000213951,28244,90.628,28706.0,168.9,31.768967
1000227914,20905,70.307,21117.0,NaN,NaN
1000227914,20746,68.492,21117.0,NaN,NaN
1000227914,20555,71.668,21117.0,NaN,NaN
1000227914,20491,68.492,21117.0,NaN,NaN
1000227914,20620,69.400,21117.0,177.8,21.953105
1000508752,24740,56.245,25212.0,160.0,21.970703
1000508752,24915,58.967,25212.0,162.6,22.303240
1000508752,24929,56.699,25212.0,162.6,21.445408
1000508752,24894,56.699,25212.0,162.6,21.445408
1000508752,24886,59.874,25212.0,162.6,22.646297
1000508752,24886,59.874,25212.0,162.6,22.646297
1000508752,24971,62.142,25212.0,162.6,23.504128
1000508752,24838,56.699,25212.0,NaN,NaN
1000508752,24755,56.245,25212.0,160.0,21.970703
1000508752,25027,62.142,25212.0,162.6,23.504128
1000508752,24810,56.699,25212.0,160.0,22.148047
1000508752,24886,59.421,25212.0,162.6,22.474957
1000508752,24886,59.421,25212.0,162.6,22.474957
1000508752,24824,56.699,25212.0,NaN,NaN
1000519317,29599,79.832,29827.0,NaN,NaN
1000519317,29599,79.832,29827.0,NaN,NaN
1000560997,13165,83.461,14214.0,172.7,27.983299
1000560997,12731,82.554,14214.0,177.8,26.114073
1000604785,24750,66.224,25239.0,NaN,NaN
1000604785,24386,62.142,25239.0,157.5,25.050945
1000604785,24826,65.771,25239.0,NaN,NaN
1000614901,30352,72.575,30566.0,167.6,25.836817
100067499,22744,79.379,24103.0,177.8,25.109734
1001181440,17579,68.039,18980.0,NaN,NaN
...,...,...,...,...,...
998484472,20473,70.307,21637.0,NaN,NaN
998484472,20426,71.668,21637.0,162.6,27.107171
998484472,21327,87.090,21637.0,NaN,NaN
998484472,21243,79.699,21637.0,NaN,NaN
998484472,21242,80.499,21637.0,NaN,NaN
998484472,21127,80.286,21637.0,170.2,27.715372
998484472,21004,84.822,21637.0,167.6,30.196769
998484472,20837,79.832,21637.0,NaN,NaN
998484472,21372,85.275,21637.0,170.0,29.506920
998646480,23265,72.575,23685.0,157.5,29.256740
998835137,21037,77.111,22164.0,170.2,26.619336
998835137,21330,79.832,22164.0,172.7,26.766546
999000191,19591,97.069,20697.0,157.5,39.130864
999000191,20310,90.718,20697.0,162.6,34.312502
999000191,20325,90.718,20697.0,162.6,34.312502
999000191,19712,96.162,20697.0,162.6,36.371600
999000191,19647,97.069,20697.0,157.5,39.130864
999000191,20369,90.718,20697.0,162.6,34.312502
999000191,18898,87.090,20697.0,165.1,31.950241
999000191,18962,86.183,20697.0,157.5,34.742454
999000191,20118,91.172,20697.0,162.6,34.484219
999008531,15763,115.666,16673.0,175.3,37.639330
999008531,15740,113.398,16673.0,175.3,36.901291
999200169,20200,55.500,22944.0,NaN,NaN
999200169,20193,54.090,22944.0,NaN,NaN
999453978,17426,101.151,18701.0,177.8,31.996809
99955976,20416,54.431,20819.0,165.1,19.968809
999939503,24642,76.204,25705.0,165.1,27.956553
999939503,24794,76.204,25705.0,165.1,27.956553
999939503,25271,79.832,25705.0,165.1,29.287538

In [4]:
BMI_Cases_1.loc[(BMI_Cases_1["HT_Onset"] - BMI_Cases_1["age_in_days"]) > 180]

,age_in_days,Weight_in_kg,HT_Onset,Height_in_cm,BMI
medical_record_number,,,,,
1000213951,28244,90.628,28706.0,168.9,31.768967
1000227914,20905,70.307,21117.0,NaN,NaN
1000227914,20746,68.492,21117.0,NaN,NaN
1000227914,20555,71.668,21117.0,NaN,NaN
1000227914,20491,68.492,21117.0,NaN,NaN
1000227914,20620,69.400,21117.0,177.8,21.953105
1000508752,24740,56.245,25212.0,160.0,21.970703
1000508752,24915,58.967,25212.0,162.6,22.303240
1000508752,24929,56.699,25212.0,162.6,21.445408
1000508752,24894,56.699,25212.0,162.6,21.445408
1000508752,24886,59.874,25212.0,162.6,22.646297
1000508752,24886,59.874,25212.0,162.6,22.646297
1000508752,24971,62.142,25212.0,162.6,23.504128
1000508752,24838,56.699,25212.0,NaN,NaN
1000508752,24755,56.245,25212.0,160.0,21.970703
1000508752,25027,62.142,25212.0,162.6,23.504128
1000508752,24810,56.699,25212.0,160.0,22.148047
1000508752,24886,59.421,25212.0,162.6,22.474957
1000508752,24886,59.421,25212.0,162.6,22.474957
1000508752,24824,56.699,25212.0,NaN,NaN
1000519317,29599,79.832,29827.0,NaN,NaN
1000519317,29599,79.832,29827.0,NaN,NaN
1000560997,13165,83.461,14214.0,172.7,27.983299
1000560997,12731,82.554,14214.0,177.8,26.114073
1000604785,24750,66.224,25239.0,NaN,NaN
1000604785,24386,62.142,25239.0,157.5,25.050945
1000604785,24826,65.771,25239.0,NaN,NaN
1000614901,30352,72.575,30566.0,167.6,25.836817
100067499,22744,79.379,24103.0,177.8,25.109734
1001181440,17579,68.039,18980.0,NaN,NaN
...,...,...,...,...,...
998484472,20473,70.307,21637.0,NaN,NaN
998484472,20426,71.668,21637.0,162.6,27.107171
998484472,21327,87.090,21637.0,NaN,NaN
998484472,21243,79.699,21637.0,NaN,NaN
998484472,21242,80.499,21637.0,NaN,NaN
998484472,21127,80.286,21637.0,170.2,27.715372
998484472,21004,84.822,21637.0,167.6,30.196769
998484472,20837,79.832,21637.0,NaN,NaN
998484472,21372,85.275,21637.0,170.0,29.506920
998646480,23265,72.575,23685.0,157.5,29.256740
998835137,21037,77.111,22164.0,170.2,26.619336
998835137,21330,79.832,22164.0,172.7,26.766546
999000191,19591,97.069,20697.0,157.5,39.130864
999000191,20310,90.718,20697.0,162.6,34.312502
999000191,20325,90.718,20697.0,162.6,34.312502
999000191,19712,96.162,20697.0,162.6,36.371600
999000191,19647,97.069,20697.0,157.5,39.130864
999000191,20369,90.718,20697.0,162.6,34.312502
999000191,18898,87.090,20697.0,165.1,31.950241
999000191,18962,86.183,20697.0,157.5,34.742454
999000191,20118,91.172,20697.0,162.6,34.484219
999008531,15763,115.666,16673.0,175.3,37.639330
999008531,15740,113.398,16673.0,175.3,36.901291
999200169,20200,55.500,22944.0,NaN,NaN
999200169,20193,54.090,22944.0,NaN,NaN
999453978,17426,101.151,18701.0,177.8,31.996809
99955976,20416,54.431,20819.0,165.1,19.968809
999939503,24642,76.204,25705.0,165.1,27.956553
999939503,24794,76.204,25705.0,165.1,27.956553
999939503,25271,79.832,25705.0,165.1,29.287538

In [ ]:
#merged Weights and Heights merging on MRN and age_in_days - important! as otherwise height and weight not from the same day are taken
BMI = Case_filtered_15_540_Weights.merge(Case_filtered_15_540_Heights, on= ['medical_record_number', 'age_in_days'], how='left')

In [ ]:
# generic function to calculate BMI
def body_mass_index(df_BMI):
    
    df = df_BMI["Weight_in_kg"].div(((df_BMI['Height_in_cm']).div(100)).pow(2))
    
    return df

In [ ]:
BMI['BMI'] = body_mass_index(BMI)
BMI_cases = BMI

In [ ]:
BMI = BMI.rename(columns={"numeric_value": "Height_in_cm","Weight": "Weight_in_kg"})

In [ ]:
BMI = BMI.drop(columns=['unit_of_measure_x'])

In [ ]:
#BMI.dropna(subset=['BMI'])

In [ ]:
#BMI_cases_1.to_parquet("BMI_cases.parquet")

In [9]:
# Get min,max,mean and create a new dataframe with these three values from the output of the function filter_df_onset
def min_max_mean(df,BMI):
    df_min = df.groupby([df["medical_record_number"]])['BMI'].min().to_frame()
    df_max = df.groupby([df["medical_record_number"]])['BMI'].max().to_frame()
    df_mean = df.groupby([df["medical_record_number"]])['BMI'].mean().to_frame()
    df_min.rename(columns={"BMI": BMI+"_min"}, inplace=True)
    df_max.rename(columns={"BMI": BMI+"_max"}, inplace=True)
    df_mean.rename(columns={"BMI": BMI+"_mean"}, inplace=True)
    result = df_min.merge(df_max, left_index=True, right_index=True)
    result = result.merge(df_mean, left_index=True, right_index=True)
    return result

In [ ]:
BMI_Cases_1 = BMI_Cases_1.reset_index('medical_record_number')

In [11]:
BMI_cases_min_max_mean = min_max_mean(BMI_Cases_1, "BMI")

In [12]:
BMI_cases_min_max_mean

                         BMI_min    BMI_max   BMI_mean
medical_record_number
1000213951             31.768967  31.768967  31.768967
1000227914             21.953105  21.953105  21.953105
1000508752             21.445408  23.504128  22.377856
1000519317                   NaN        NaN        NaN
1000560997             26.114073  27.983299  27.048686
1000604785             25.050945  25.050945  25.050945
1000614901             25.836817  25.836817  25.836817
100067499              25.109734  25.109734  25.109734
1001181440                   NaN        NaN        NaN
1001238837             27.450228  30.353641  29.220766
1001444893             28.474481  30.779546  29.728725
1002038565                   NaN        NaN        NaN
1002080058             41.177283  41.177283  41.177283
1002130098             25.793152  25.793152  25.793152
1002135835                   NaN        NaN        NaN
100242293              20.825710  29.066108  24.401610
1002485877                   NaN        NaN        NaN
1002642963             16.632396  18.408844  17.520620
1002762576             28.135519  28.135519  28.135519
1002845799             29.490694  29.490694  29.490694
1003009291                   NaN        NaN        NaN
1003204795             27.956553  30.452333  29.102720
1003511919             21.632907  23.297005  22.631329
1003817301             23.033984  23.033984  23.033984
1004191751             22.569236  26.324871  24.117258
1004930426             38.738900  38.738900  38.738900
1004943930             24.740369  25.490004  25.115186
1005115509             29.022622  29.022622  29.022622
1005265249             28.625841  28.625841  28.625841
1005529584             23.575851  23.575851  23.575851
...                          ...        ...        ...
994885287              27.307112  28.135519  27.721315
995147103              30.322381  30.322381  30.322381
99542555               21.719143  23.063256  22.629718
995573558              25.654489  29.696529  27.024505
995582597              50.703125  50.703125  50.703125
995597596              26.223437  26.400391  26.299184
995728959              21.623781  21.623781  21.623781
996137149                    NaN        NaN        NaN
99632877               46.829165  46.829165  46.829165
99641279               29.679908  29.679908  29.679908
997080012              41.690703  41.690703  41.690703
997193359              27.450228  27.450228  27.450228
997373025              25.514453  25.514453  25.514453
99768819               35.918548  35.918548  35.918548
997732196              33.487664  33.766672  33.580667
99779652               30.690375  30.690375  30.690375
997815476              29.751064  29.751064  29.751064
997905577              28.289299  28.289299  28.289299
997925088              26.950543  28.371555  27.661049
998152397              31.566288  31.566288  31.566288
998356589              20.445691  20.445691  20.445691
998484472              27.107171  30.196769  28.616976
998646480              29.256740  29.256740  29.256740
998835137              26.619336  26.766546  26.692941
999000191              31.950241  39.130864  35.416416
999008531              36.901291  37.639330  37.270311
999200169                    NaN        NaN        NaN
999453978              31.996809  31.996809  31.996809
99955976               19.968809  19.968809  19.968809
999939503              27.956553  29.287538  28.400215

[21431 rows x 3 columns]

In [ ]:
### BMI Controls ###

In [14]:
# read control dataframe into it - where multiple MRNs exist and age_in_days
BMI_Control_1 = pq.read_table('Cohorts/Control/Measurement/BMI/BMI_controls_filtered_15_540.parquet').to_pandas()

In [19]:
# Get min,max,mean and create a new dataframe with these three values from the output of the function filter_df_onset
def min_max_mean(df,BMI):
    df_min = df.groupby([df["medical_record_number"]])['BMI'].min().to_frame()
    df_max = df.groupby([df["medical_record_number"]])['BMI'].max().to_frame()
    df_mean = df.groupby([df["medical_record_number"]])['BMI'].mean().to_frame()
    df_min.rename(columns={"BMI": BMI+"_min"}, inplace=True)
    df_max.rename(columns={"BMI": BMI+"_max"}, inplace=True)
    df_mean.rename(columns={"BMI": BMI+"_mean"}, inplace=True)
    result = df_min.merge(df_max, left_index=True, right_index=True)
    result = result.merge(df_mean, left_index=True, right_index=True)
    return result

In [ ]:
BMI_Control_1 = BMI_Control_1.reset_index('medical_record_number')

In [21]:
BMI_Control_min_max_mean = min_max_mean(BMI_Control_1, "BMI")

In [22]:
BMI_Control_min_max_mean

                         BMI_min      BMI_max    BMI_mean
medical_record_number
1000004097             23.800713    23.800713   23.800713
1000020255             23.222373    32.730864   28.357303
100002558              24.544888    24.544888   24.544888
100002884              33.642758    38.258602   36.118211
1000044143             19.382615    21.172784   19.864298
1000045212             18.946743    19.886054   19.334513
1000064392             25.634295    26.983566   26.193533
1000068212             31.004181    31.662039   31.333110
1000079798             16.256957    22.234849   20.449918
1000083464             29.846367    29.846367   29.846367
1000086416             23.414582    23.414582   23.414582
100009847              41.984695    43.599518   42.616357
1000098914             20.700440    22.193910   21.680799
1000119948             23.616917    25.388146   24.502487
1000124322             21.211187    24.136659   23.161502
1000127842             25.249022    30.999746   28.793398
1000129011             15.304561    35.726318   30.039071
1000133396             24.333376    24.333376   24.333376
1000144873             17.971965    18.371481   18.171723
1000165222             23.259949  3349.432699  190.742549
1000172084             15.702117    22.849032   17.875393
1000182120             25.854233    29.256629   27.215609
1000199143             14.903710    15.678917   15.432920
1000204228              2.230437     2.230437    2.230437
1000205924             21.960183    27.793285   24.713716
1000221305             25.141845    26.644229   25.891221
1000226045             22.646297    24.018903   23.412717
1000238281             29.124511    31.972861   30.498819
1000248852             28.323489    28.323489   28.323489
10002550               30.857117    31.442674   31.149896
...                          ...          ...         ...
999602917              32.893626    33.838862   33.523784
999610730              24.867781    25.352299   25.110040
999626535              24.451562    26.330864   25.438282
999717070              19.968809    21.300161   20.578966
999737209              24.406911    24.406911   24.406911
999766315              33.357339    34.293172   33.825255
999766904              21.533120    24.961103   23.290000
999772628              21.102351    24.705016   23.112036
999778207              20.800858    21.300161   21.133696
999788884              19.674180    24.391988   20.754942
999793946              22.843764    22.843764   22.843764
999805131              22.681406    27.223348   24.161213
99980583               25.959342    29.454094   27.413804
999822379              23.572948    24.333376   23.775740
999833175              28.703906    31.007422   29.855664
999849522                    NaN          NaN         NaN
999883355              23.954044    24.502293   24.319543
99990591               21.788465    22.146860   21.967663
999910636              20.587577    20.587577   20.587577
999928563              22.464956    28.891166   26.144436
999930578              20.982089    28.581946   24.980576
999931584              20.657710    20.657710   20.657710
999934212              27.817969    29.235547   28.455937
999943717              24.451562    26.400391   25.479018
999965532                    NaN          NaN         NaN
999983604              17.649465    22.391574   20.238740
99998366               19.948882    22.547953   21.332183
999983785              30.533995    41.984695   34.138740
999987586              34.446388    34.521596   34.483992
99999223               30.690375    32.882446   31.755100

[415883 rows x 3 columns]